from turtle import *
import random
from time import * 
speed(0)

def people():
    penup()
    goto(-220, 50)
    pendown()
    right(90)
    forward(75)
    back(75)
    left(90)
    circle(25)
    right(90)
    forward(25)
    right(135)
    forward(50)
    back(50)
    right(90)
    forward(50)
    back(50)
    right(135)
    forward(50)
    right(30)
    forward(50)
    back(50)
    left(60)
    forward(50)
    left(60)




def car(time):
    pensize(5)
    penup()
    goto(-140 + time * 60, -70)
    pendown()
    color("white")
    begin_fill()
    forward(200)
    left(90)
    forward(200)
    left(90)
    forward(200)
    left(90)
    forward(200)
    left(90)
    end_fill()
    pensize(5)
    penup()
    goto(-200 + time * 60, -50)
    pendown()
    color("gray")
    forward(200)
    left(90)
    forward(50)
    left(90)
    forward(200)
    left(90)
    forward(50)
    left(90)
    penup()
    goto(-170 + time * 60, 0)
    pendown()
    forward(140)
    left(90)
    forward(30)
    left(90)
    forward(140)
    left(90)
    forward(30)
    left(90)
    penup()
    goto(-150 + time * 60, -60)
    pendown()
    color("black")
    circle(20)
    penup()
    goto(-50 + time * 60, -60)
    pendown()
    circle(20)

def last_car():
    pensize(5)
    penup()
    goto(-140, -70)
    pendown()
    color("white")
    begin_fill()
    forward(200)
    left(90)
    forward(200)
    left(90)
    forward(200)
    left(90)
    forward(200)
    left(90)
    end_fill()
    pensize(5)
    penup()
    goto(-190, -50)
    pendown()
    color("red")
    forward(200)
    left(90)
    forward(50)
    left(90)
    forward(200)
    left(90)
    forward(50)
    left(90)
    penup()
    goto(-160, 0)
    pendown()
    forward(140)
    left(90)
    forward(30)
    left(90)
    forward(140)
    left(90)
    forward(30)
    left(90)
    penup()
    goto(-140, -60)
    pendown()
    color("black")
    circle(20)
    penup()
    goto(-40, -60)
    pendown()
    circle(20)

def draw_blood_splatter():
    color("red")
    hideturtle()
    penup()
    goto(-200, 0)
    pendown()
    begin_fill()
    circle(5)
    end_fill()

    for _ in range(30): 
        angle = random.randint(0, 360) 
        distance = random.randint(30, 150)
        size = random.randint(1, 3)

        penup()
        setheading(angle)
        forward(distance)
        pendown()
        begin_fill()
        circle(size) 
        end_fill()
        penup()
        goto(-200, 0)

def solution(solution):
    penup()
    goto(-300, 200)
    pendown()
    num_letters = len(solution)
    in_progress = list( '_'*num_letters )
    for _ in in_progress:
        write("_", align='left', font=('Arial', 30, 'normal'))
        penup()
        forward(25)
        pendown()

def left_time(time):
    penup()
    goto(50,255)
    pendown()
    color("white")
    write( "your left time :" + str(time + 1), align='left', font=('Arial', 30, 'normal'))
    color("black")
    write( "your left time :" + str(time), align='left', font=('Arial', 30, 'normal'))

def question():
        ques = textinput("your question", "input here")
        print(ques)
        return ques

def answer(solution):
    solution_list = list(solution)
    i = 5
    correct_count = 0
    left_time(5)
    while i > 0:
        ans_letter = textinput("your answer", "input here")
        if ans_letter in solution_list:
            while ans_letter in solution_list:
                correct_count += 1

                penup()
                goto(-300, 205)
                forward(25*solution_list.index(ans_letter))
                pendown()
                write(ans_letter, align='left', font=('Arial', 30, 'normal'))
                solution_list[solution_list.index(ans_letter)] = None
                penup()
                goto(-300, 205)
                pendown()
            if correct_count == len(solution):
                penup()
                goto(-250, -200)
                pendown()
                write("SUCCESS", align='left', font=('Arial', 100, 'normal'))
                return
            
        else:
            i -= 1
            left_time(i)
            if i > 0:
                car(i)   
        sleep(0.5)

    last_car()
    draw_blood_splatter()
    penup()
    goto(-150, -200)
    pendown()
    write("Failed", align='left', font=('Arial', 100, 'normal'))

ques = question()
people()
car(5)
solution(ques)
answer(ques)

done()